services:
  php: 
    build: ./php-image
    container_name: php
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache2:/etc/apache2
    environment:
      TZ: "America/New_York"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '{{root password}}'
      MYSQL_USER: '{{ user name }}'
      MYSQL_PASSWORD: '{{ user password }}'
      MYSQL_DATABASE: '{{ user db }}'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini